#!/usr/bin/env node
/**
 * Fix scrambled tag translations in 13 locale files.
 * The middle 41 tags (tag_action through tag_words) got circular-swapped
 * between locales. This script replaces them with correct translations.
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const LOCALES_DIR = resolve(__dirname, '..', 'client', 'src', 'contexts', 'locales');

// Correct tag translations for each broken locale.
// These are the 41 middle tags: tag_action → tag_words (in file order: tag_3d, tag_action, ... tag_words)
// Actually the affected block is tag_action through tag_words (lines ~404-444)
// Let me define the correct translations for each locale.

const CORRECT_TAGS = {
  ar: {
    'tag_3d': '3D',
    'tag_action': 'أكشن',
    'tag_adventure': 'مغامرة',
    'tag_aiming': 'تصويب',
    'tag_arcade': 'آركيد',
    'tag_brain': 'ذهني',
    'tag_brainTeaser': 'ألغاز',
    'tag_cards': 'بطاقات',
    'tag_catching': 'التقاط',
    'tag_classic': 'كلاسيكي',
    'tag_clicking': 'نقر',
    'tag_cute': 'لطيف',
    'tag_daily': 'يومي',
    'tag_fighting': 'قتال',
    'tag_food': 'طعام',
    'tag_french': 'فرنسي',
    'tag_funny': 'مضحك',
    'tag_geography': 'جغرافيا',
    'tag_history': 'تاريخ',
    'tag_launching': 'إطلاق',
    'tag_logic': 'منطق',
    'tag_maze': 'متاهة',
    'tag_miniGames': 'ألعاب صغيرة',
    'tag_mouse': 'فأرة',
    'tag_nature': 'طبيعة',
    'tag_platformer': 'منصات',
    'tag_pointAndClick': 'أشر وانقر',
    'tag_precision': 'دقة',
    'tag_puzzle': 'أحجية',
    'tag_rpg': 'RPG',
    'tag_runner': 'عدّاء',
    'tag_sciFi': 'خيال علمي',
    'tag_shooter': 'تصويب',
    'tag_social': 'اجتماعي',
    'tag_strategy': 'استراتيجية',
    'tag_summer': 'صيف',
    'tag_timing': 'توقيت',
    'tag_typing': 'كتابة',
    'tag_vsAi': 'ضد الذكاء الاصطناعي',
    'tag_weapons': 'أسلحة',
    'tag_words': 'كلمات',
  },
  hi: {
    'tag_3d': '3D',
    'tag_action': 'एक्शन',
    'tag_adventure': 'साहसिक',
    'tag_aiming': 'निशाना',
    'tag_arcade': 'आर्केड',
    'tag_brain': 'दिमाग',
    'tag_brainTeaser': 'पहेली',
    'tag_cards': 'ताश',
    'tag_catching': 'पकड़ना',
    'tag_classic': 'क्लासिक',
    'tag_clicking': 'क्लिक',
    'tag_cute': 'प्यारा',
    'tag_daily': 'दैनिक',
    'tag_fighting': 'लड़ाई',
    'tag_food': 'भोजन',
    'tag_french': 'फ्रेंच',
    'tag_funny': 'मज़ेदार',
    'tag_geography': 'भूगोल',
    'tag_history': 'इतिहास',
    'tag_launching': 'प्रक्षेपण',
    'tag_logic': 'तर्क',
    'tag_maze': 'भूलभुलैया',
    'tag_miniGames': 'छोटे खेल',
    'tag_mouse': 'माउस',
    'tag_nature': 'प्रकृति',
    'tag_platformer': 'प्लेटफ़ॉर्मर',
    'tag_pointAndClick': 'पॉइंट एंड क्लिक',
    'tag_precision': 'सटीकता',
    'tag_puzzle': 'पज़ल',
    'tag_rpg': 'RPG',
    'tag_runner': 'रनर',
    'tag_sciFi': 'साइ-फ़ाई',
    'tag_shooter': 'शूटर',
    'tag_social': 'सामाजिक',
    'tag_strategy': 'रणनीति',
    'tag_summer': 'गर्मी',
    'tag_timing': 'समय',
    'tag_typing': 'टाइपिंग',
    'tag_vsAi': 'AI के ख़िलाफ़',
    'tag_weapons': 'हथियार',
    'tag_words': 'शब्द',
  },
  tr: {
    'tag_3d': '3D',
    'tag_action': 'Aksiyon',
    'tag_adventure': 'Macera',
    'tag_aiming': 'Nişan Alma',
    'tag_arcade': 'Arcade',
    'tag_brain': 'Beyin',
    'tag_brainTeaser': 'Bulmaca',
    'tag_cards': 'Kart',
    'tag_catching': 'Yakalama',
    'tag_classic': 'Klasik',
    'tag_clicking': 'Tıklama',
    'tag_cute': 'Sevimli',
    'tag_daily': 'Günlük',
    'tag_fighting': 'Dövüş',
    'tag_food': 'Yemek',
    'tag_french': 'Fransız',
    'tag_funny': 'Eğlenceli',
    'tag_geography': 'Coğrafya',
    'tag_history': 'Tarih',
    'tag_launching': 'Fırlatma',
    'tag_logic': 'Mantık',
    'tag_maze': 'Labirent',
    'tag_miniGames': 'Mini Oyunlar',
    'tag_mouse': 'Fare',
    'tag_nature': 'Doğa',
    'tag_platformer': 'Platform',
    'tag_pointAndClick': 'Tıkla ve İşaretle',
    'tag_precision': 'Hassasiyet',
    'tag_puzzle': 'Bulmaca',
    'tag_rpg': 'RPG',
    'tag_runner': 'Koşu',
    'tag_sciFi': 'Bilim Kurgu',
    'tag_shooter': 'Nişancı',
    'tag_social': 'Sosyal',
    'tag_strategy': 'Strateji',
    'tag_summer': 'Yaz',
    'tag_timing': 'Zamanlama',
    'tag_typing': 'Yazma',
    'tag_vsAi': 'Yapay Zekaya Karşı',
    'tag_weapons': 'Silahlar',
    'tag_words': 'Kelimeler',
  },
  nl: {
    'tag_3d': '3D',
    'tag_action': 'Actie',
    'tag_adventure': 'Avontuur',
    'tag_aiming': 'Mikken',
    'tag_arcade': 'Arcade',
    'tag_brain': 'Brein',
    'tag_brainTeaser': 'Hersenkraker',
    'tag_cards': 'Kaarten',
    'tag_catching': 'Vangen',
    'tag_classic': 'Klassiek',
    'tag_clicking': 'Klikken',
    'tag_cute': 'Schattig',
    'tag_daily': 'Dagelijks',
    'tag_fighting': 'Vechten',
    'tag_food': 'Eten',
    'tag_french': 'Frans',
    'tag_funny': 'Grappig',
    'tag_geography': 'Aardrijkskunde',
    'tag_history': 'Geschiedenis',
    'tag_launching': 'Lancering',
    'tag_logic': 'Logica',
    'tag_maze': 'Doolhof',
    'tag_miniGames': 'Minispellen',
    'tag_mouse': 'Muis',
    'tag_nature': 'Natuur',
    'tag_platformer': 'Platformer',
    'tag_pointAndClick': 'Klik en Wijs',
    'tag_precision': 'Precisie',
    'tag_puzzle': 'Puzzel',
    'tag_rpg': 'RPG',
    'tag_runner': 'Hardlopen',
    'tag_sciFi': 'Sciencefiction',
    'tag_shooter': 'Schieten',
    'tag_social': 'Sociaal',
    'tag_strategy': 'Strategie',
    'tag_summer': 'Zomer',
    'tag_timing': 'Timing',
    'tag_typing': 'Typen',
    'tag_vsAi': 'Tegen AI',
    'tag_weapons': 'Wapens',
    'tag_words': 'Woorden',
  },
  pl: {
    'tag_3d': '3D',
    'tag_action': 'Akcja',
    'tag_adventure': 'Przygoda',
    'tag_aiming': 'Celowanie',
    'tag_arcade': 'Arcade',
    'tag_brain': 'Umysł',
    'tag_brainTeaser': 'Łamigłówka',
    'tag_cards': 'Karty',
    'tag_catching': 'Łapanie',
    'tag_classic': 'Klasyka',
    'tag_clicking': 'Klikanie',
    'tag_cute': 'Urocze',
    'tag_daily': 'Codzienne',
    'tag_fighting': 'Walka',
    'tag_food': 'Jedzenie',
    'tag_french': 'Francuski',
    'tag_funny': 'Zabawne',
    'tag_geography': 'Geografia',
    'tag_history': 'Historia',
    'tag_launching': 'Wystrzeliwanie',
    'tag_logic': 'Logika',
    'tag_maze': 'Labirynt',
    'tag_miniGames': 'Minigry',
    'tag_mouse': 'Mysz',
    'tag_nature': 'Natura',
    'tag_platformer': 'Platformówka',
    'tag_pointAndClick': 'Wskaż i kliknij',
    'tag_precision': 'Precyzja',
    'tag_puzzle': 'Puzzle',
    'tag_rpg': 'RPG',
    'tag_runner': 'Biegacz',
    'tag_sciFi': 'Sci-Fi',
    'tag_shooter': 'Strzelanka',
    'tag_social': 'Społeczne',
    'tag_strategy': 'Strategia',
    'tag_summer': 'Lato',
    'tag_timing': 'Wyczucie czasu',
    'tag_typing': 'Pisanie',
    'tag_vsAi': 'Przeciw AI',
    'tag_weapons': 'Broń',
    'tag_words': 'Słowa',
  },
  sv: {
    'tag_3d': '3D',
    'tag_action': 'Action',
    'tag_adventure': 'Äventyr',
    'tag_aiming': 'Sikta',
    'tag_arcade': 'Arkad',
    'tag_brain': 'Hjärna',
    'tag_brainTeaser': 'Knepig',
    'tag_cards': 'Kort',
    'tag_catching': 'Fånga',
    'tag_classic': 'Klassiker',
    'tag_clicking': 'Klicka',
    'tag_cute': 'Gulligt',
    'tag_daily': 'Dagligt',
    'tag_fighting': 'Strid',
    'tag_food': 'Mat',
    'tag_french': 'Franskt',
    'tag_funny': 'Roligt',
    'tag_geography': 'Geografi',
    'tag_history': 'Historia',
    'tag_launching': 'Avfyrning',
    'tag_logic': 'Logik',
    'tag_maze': 'Labyrint',
    'tag_miniGames': 'Minispel',
    'tag_mouse': 'Mus',
    'tag_nature': 'Natur',
    'tag_platformer': 'Plattform',
    'tag_pointAndClick': 'Peka och klicka',
    'tag_precision': 'Precision',
    'tag_puzzle': 'Pussel',
    'tag_rpg': 'RPG',
    'tag_runner': 'Löpare',
    'tag_sciFi': 'Sci-fi',
    'tag_shooter': 'Skjutare',
    'tag_social': 'Socialt',
    'tag_strategy': 'Strategi',
    'tag_summer': 'Sommar',
    'tag_timing': 'Tajming',
    'tag_typing': 'Skrivning',
    'tag_vsAi': 'Mot AI',
    'tag_weapons': 'Vapen',
    'tag_words': 'Ord',
  },
  id: {
    'tag_3d': '3D',
    'tag_action': 'Aksi',
    'tag_adventure': 'Petualangan',
    'tag_aiming': 'Membidik',
    'tag_arcade': 'Arcade',
    'tag_brain': 'Otak',
    'tag_brainTeaser': 'Asah Otak',
    'tag_cards': 'Kartu',
    'tag_catching': 'Menangkap',
    'tag_classic': 'Klasik',
    'tag_clicking': 'Klik',
    'tag_cute': 'Lucu',
    'tag_daily': 'Harian',
    'tag_fighting': 'Pertarungan',
    'tag_food': 'Makanan',
    'tag_french': 'Prancis',
    'tag_funny': 'Lucu',
    'tag_geography': 'Geografi',
    'tag_history': 'Sejarah',
    'tag_launching': 'Peluncuran',
    'tag_logic': 'Logika',
    'tag_maze': 'Labirin',
    'tag_miniGames': 'Mini Game',
    'tag_mouse': 'Mouse',
    'tag_nature': 'Alam',
    'tag_platformer': 'Platform',
    'tag_pointAndClick': 'Tunjuk dan Klik',
    'tag_precision': 'Presisi',
    'tag_puzzle': 'Teka-teki',
    'tag_rpg': 'RPG',
    'tag_runner': 'Lari',
    'tag_sciFi': 'Fiksi Ilmiah',
    'tag_shooter': 'Tembak-tembakan',
    'tag_social': 'Sosial',
    'tag_strategy': 'Strategi',
    'tag_summer': 'Musim Panas',
    'tag_timing': 'Ketepatan Waktu',
    'tag_typing': 'Mengetik',
    'tag_vsAi': 'Lawan AI',
    'tag_weapons': 'Senjata',
    'tag_words': 'Kata',
  },
  vi: {
    'tag_3d': '3D',
    'tag_action': 'Hành động',
    'tag_adventure': 'Phiêu lưu',
    'tag_aiming': 'Ngắm bắn',
    'tag_arcade': 'Arcade',
    'tag_brain': 'Trí tuệ',
    'tag_brainTeaser': 'Đố mẹo',
    'tag_cards': 'Bài',
    'tag_catching': 'Bắt',
    'tag_classic': 'Cổ điển',
    'tag_clicking': 'Nhấp chuột',
    'tag_cute': 'Dễ thương',
    'tag_daily': 'Hàng ngày',
    'tag_fighting': 'Chiến đấu',
    'tag_food': 'Ẩm thực',
    'tag_french': 'Pháp',
    'tag_funny': 'Hài hước',
    'tag_geography': 'Địa lý',
    'tag_history': 'Lịch sử',
    'tag_launching': 'Phóng',
    'tag_logic': 'Logic',
    'tag_maze': 'Mê cung',
    'tag_miniGames': 'Trò chơi nhỏ',
    'tag_mouse': 'Chuột',
    'tag_nature': 'Thiên nhiên',
    'tag_platformer': 'Nhảy đạp',
    'tag_pointAndClick': 'Trỏ và nhấp',
    'tag_precision': 'Chính xác',
    'tag_puzzle': 'Xếp hình',
    'tag_rpg': 'RPG',
    'tag_runner': 'Chạy',
    'tag_sciFi': 'Viễn tưởng',
    'tag_shooter': 'Bắn súng',
    'tag_social': 'Xã hội',
    'tag_strategy': 'Chiến lược',
    'tag_summer': 'Mùa hè',
    'tag_timing': 'Canh thời gian',
    'tag_typing': 'Gõ phím',
    'tag_vsAi': 'Đấu AI',
    'tag_weapons': 'Vũ khí',
    'tag_words': 'Từ vựng',
  },
  th: {
    'tag_3d': '3D',
    'tag_action': 'แอคชั่น',
    'tag_adventure': 'ผจญภัย',
    'tag_aiming': 'เล็ง',
    'tag_arcade': 'อาร์เคด',
    'tag_brain': 'สมอง',
    'tag_brainTeaser': 'ปริศนา',
    'tag_cards': 'ไพ่',
    'tag_catching': 'จับ',
    'tag_classic': 'คลาสสิก',
    'tag_clicking': 'คลิก',
    'tag_cute': 'น่ารัก',
    'tag_daily': 'ประจำวัน',
    'tag_fighting': 'ต่อสู้',
    'tag_food': 'อาหาร',
    'tag_french': 'ฝรั่งเศส',
    'tag_funny': 'ตลก',
    'tag_geography': 'ภูมิศาสตร์',
    'tag_history': 'ประวัติศาสตร์',
    'tag_launching': 'ปล่อย',
    'tag_logic': 'ตรรกะ',
    'tag_maze': 'เขาวงกต',
    'tag_miniGames': 'มินิเกม',
    'tag_mouse': 'เมาส์',
    'tag_nature': 'ธรรมชาติ',
    'tag_platformer': 'แพลตฟอร์ม',
    'tag_pointAndClick': 'ชี้แล้วคลิก',
    'tag_precision': 'ความแม่นยำ',
    'tag_puzzle': 'ปริศนา',
    'tag_rpg': 'RPG',
    'tag_runner': 'วิ่ง',
    'tag_sciFi': 'ไซไฟ',
    'tag_shooter': 'ยิง',
    'tag_social': 'สังคม',
    'tag_strategy': 'กลยุทธ์',
    'tag_summer': 'ฤดูร้อน',
    'tag_timing': 'จับจังหวะ',
    'tag_typing': 'พิมพ์',
    'tag_vsAi': 'สู้กับ AI',
    'tag_weapons': 'อาวุธ',
    'tag_words': 'คำศัพท์',
  },
  'zh-CN': {
    'tag_3d': '3D',
    'tag_action': '动作',
    'tag_adventure': '冒险',
    'tag_aiming': '瞄准',
    'tag_arcade': '街机',
    'tag_brain': '脑力',
    'tag_brainTeaser': '脑筋急转弯',
    'tag_cards': '纸牌',
    'tag_catching': '接住',
    'tag_classic': '经典',
    'tag_clicking': '点击',
    'tag_cute': '可爱',
    'tag_daily': '每日',
    'tag_fighting': '格斗',
    'tag_food': '美食',
    'tag_french': '法式',
    'tag_funny': '搞笑',
    'tag_geography': '地理',
    'tag_history': '历史',
    'tag_launching': '发射',
    'tag_logic': '逻辑',
    'tag_maze': '迷宫',
    'tag_miniGames': '小游戏',
    'tag_mouse': '鼠标',
    'tag_nature': '自然',
    'tag_platformer': '平台',
    'tag_pointAndClick': '指点点击',
    'tag_precision': '精准',
    'tag_puzzle': '拼图',
    'tag_rpg': 'RPG',
    'tag_runner': '跑酷',
    'tag_sciFi': '科幻',
    'tag_shooter': '射击',
    'tag_social': '社交',
    'tag_strategy': '策略',
    'tag_summer': '夏季',
    'tag_timing': '时机',
    'tag_typing': '打字',
    'tag_vsAi': '对战AI',
    'tag_weapons': '武器',
    'tag_words': '文字',
  },
  'zh-TW': {
    'tag_3d': '3D',
    'tag_action': '動作',
    'tag_adventure': '冒險',
    'tag_aiming': '瞄準',
    'tag_arcade': '街機',
    'tag_brain': '腦力',
    'tag_brainTeaser': '腦筋急轉彎',
    'tag_cards': '紙牌',
    'tag_catching': '接住',
    'tag_classic': '經典',
    'tag_clicking': '點擊',
    'tag_cute': '可愛',
    'tag_daily': '每日',
    'tag_fighting': '格鬥',
    'tag_food': '美食',
    'tag_french': '法式',
    'tag_funny': '搞笑',
    'tag_geography': '地理',
    'tag_history': '歷史',
    'tag_launching': '發射',
    'tag_logic': '邏輯',
    'tag_maze': '迷宮',
    'tag_miniGames': '小遊戲',
    'tag_mouse': '滑鼠',
    'tag_nature': '自然',
    'tag_platformer': '平台',
    'tag_pointAndClick': '指向點擊',
    'tag_precision': '精準',
    'tag_puzzle': '拼圖',
    'tag_rpg': 'RPG',
    'tag_runner': '跑酷',
    'tag_sciFi': '科幻',
    'tag_shooter': '射擊',
    'tag_social': '社交',
    'tag_strategy': '策略',
    'tag_summer': '夏季',
    'tag_timing': '時機',
    'tag_typing': '打字',
    'tag_vsAi': '對戰AI',
    'tag_weapons': '武器',
    'tag_words': '文字',
  },
  ja: {
    'tag_3d': '3D',
    'tag_action': 'アクション',
    'tag_adventure': 'アドベンチャー',
    'tag_aiming': 'エイミング',
    'tag_arcade': 'アーケード',
    'tag_brain': '脳トレ',
    'tag_brainTeaser': '頭の体操',
    'tag_cards': 'カード',
    'tag_catching': 'キャッチ',
    'tag_classic': 'クラシック',
    'tag_clicking': 'クリック',
    'tag_cute': 'かわいい',
    'tag_daily': 'デイリー',
    'tag_fighting': '格闘',
    'tag_food': 'フード',
    'tag_french': 'フランス',
    'tag_funny': 'おもしろい',
    'tag_geography': '地理',
    'tag_history': '歴史',
    'tag_launching': '発射',
    'tag_logic': 'ロジック',
    'tag_maze': '迷路',
    'tag_miniGames': 'ミニゲーム',
    'tag_mouse': 'マウス',
    'tag_nature': '自然',
    'tag_platformer': 'プラットフォーム',
    'tag_pointAndClick': 'ポイント&クリック',
    'tag_precision': '精密',
    'tag_puzzle': 'パズル',
    'tag_rpg': 'RPG',
    'tag_runner': 'ランナー',
    'tag_sciFi': 'SF',
    'tag_shooter': 'シューター',
    'tag_social': 'ソーシャル',
    'tag_strategy': '戦略',
    'tag_summer': '夏',
    'tag_timing': 'タイミング',
    'tag_typing': 'タイピング',
    'tag_vsAi': 'AI対戦',
    'tag_weapons': '武器',
    'tag_words': '言葉',
  },
  ko: {
    'tag_3d': '3D',
    'tag_action': '액션',
    'tag_adventure': '모험',
    'tag_aiming': '조준',
    'tag_arcade': '아케이드',
    'tag_brain': '두뇌',
    'tag_brainTeaser': '두뇌 퀴즈',
    'tag_cards': '카드',
    'tag_catching': '잡기',
    'tag_classic': '클래식',
    'tag_clicking': '클릭',
    'tag_cute': '귀여운',
    'tag_daily': '매일',
    'tag_fighting': '격투',
    'tag_food': '음식',
    'tag_french': '프랑스',
    'tag_funny': '재미있는',
    'tag_geography': '지리',
    'tag_history': '역사',
    'tag_launching': '발사',
    'tag_logic': '논리',
    'tag_maze': '미로',
    'tag_miniGames': '미니 게임',
    'tag_mouse': '마우스',
    'tag_nature': '자연',
    'tag_platformer': '플랫포머',
    'tag_pointAndClick': '포인트 앤 클릭',
    'tag_precision': '정밀',
    'tag_puzzle': '퍼즐',
    'tag_rpg': 'RPG',
    'tag_runner': '러너',
    'tag_sciFi': 'SF',
    'tag_shooter': '슈팅',
    'tag_social': '소셜',
    'tag_strategy': '전략',
    'tag_summer': '여름',
    'tag_timing': '타이밍',
    'tag_typing': '타이핑',
    'tag_vsAi': 'AI 대전',
    'tag_weapons': '무기',
    'tag_words': '단어',
  },
};

// For each broken locale, replace the wrong tags
for (const [locale, correctTags] of Object.entries(CORRECT_TAGS)) {
  const filePath = resolve(LOCALES_DIR, `${locale}.ts`);
  let content = readFileSync(filePath, 'utf-8');
  
  let replacements = 0;
  for (const [key, value] of Object.entries(correctTags)) {
    // Match the tag line with any current value
    const regex = new RegExp(`(\\s*'${key}':\\s*')([^']*)(')`, 'g');
    const newContent = content.replace(regex, (match, prefix, _oldValue, suffix) => {
      replacements++;
      return `${prefix}${value}${suffix}`;
    });
    content = newContent;
  }
  
  writeFileSync(filePath, content, 'utf-8');
  console.log(`✅ ${locale}.ts — ${replacements} tag translations fixed`);
}

console.log('\nDone! All tag translations corrected.');
